---
name: dive
description: dive
inputs:
  image:
    description: image
    required: true
runs:
  using: 'composite'
  steps:
    - uses: docker://wagoodman/dive:v0.11.0
      with:
        #entrypoint: /bin/bash
        args: CI=true dive ${{ inputs.image }}
