---
name: dive
description: dive
inputs:
  image:
    description: image
    required: true
runs:
  using: 'composite'
  steps:
    - run: docker build -t ${{ inputs.image }} .
      shell: bash
    - uses: docker://wagoodman/dive:v0.11.0
      with:
        args: ${{ inputs.image }} --ci
